#!/usr/bin/env python

import sys
from googletrans import Translator

class Et():
    def __init__(self, src):
        self.src = src
        self.translator = Translator()

    @property
    def language(self):
        return self.translator.detect(self.src).lang

    @property
    def dest(self):
        if self.language != 'en':
            return 'en'
        else:
            return 'zh-CN'

    def translate(self):
        translation = self.translator.translate(self.src, dest=self.dest)
        print(translation.text)

if __name__ == '__main__':
    Et(' '.join(sys.argv[1:])).translate()